// <auto-generated />
using MaestroCuentas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaestroCuentas.Data.Migrations
{
    [DbContext(typeof(MaestroCuentasDBContext))]
    partial class MaestroCuentasDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaestroCuentas.Data.Modelos.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<int>("CuentaTipoId");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("CuentaTipoId");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("MaestroCuentas.Data.Modelos.CuentaTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("CuentaTipo");
                });

            modelBuilder.Entity("MaestroCuentas.Data.Modelos.Cuenta", b =>
                {
                    b.HasOne("MaestroCuentas.Data.Modelos.CuentaTipo", "Cuentatipo")
                        .WithMany("Cuentas")
                        .HasForeignKey("CuentaTipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
